<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\ERCMS.Domain\ERCMS.Domain.csproj" />
      <ProjectReference Include="..\ERCMS.Infrastructure\ERCMS.Infrastructure.csproj" />
    </ItemGroup>

</Project>
